[package]
name = "rottnest_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rottnest_rs"
crate-type = ["cdylib"]

[features]
default = []
py = ["dep:pyo3", "pyarrow"]
pyarrow = ["arrow/pyarrow"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"], optional = true }
arrow = { version = "50.0.0", default-features = false }
tantivy = "0.21.1"
tantivy-jieba = "0.10.0"
whatlang = "0.16.4"
opendal = "0"
zstd = "0.13.0"                                                                 # Check for the latest version of zstd crate
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"                                                                 # For serialization and deserialization
regex = "1.5"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
lazy_static = "1"
bytes = "1"
thiserror = "1"

arrow-array = "50.0.0"
parquet = { version = "50.0.0", features = [
    "arrow",
    "async",
    "experimental",
    "test_common",
] }
async-trait = "0.1.77"
arrow-schema = "50.0.0"
snap = { version = "1.0", default-features = false, optional = true }
brotli = { version = "3.3", default-features = false, features = [
    "std",
], optional = true }
flate2 = { version = "1.0", default-features = true, features = [
    "rust_backend",
], optional = true }
lz4_flex = { version = "0.11", default-features = false, features = [
    "std",
    "frame",
], optional = true }
thrift = { version = "0.17.0" }
itertools = "0.12.1"

tokio-stream = "0.1.14"
futures = "0.3"
rand = "0.8.5"
