[package]
name = "rottnest_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rottnest_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
arrow = { version = "50.0.0", features = ["pyarrow"] }
tantivy = "0.15"
tantivy-jieba = "0.8.0"
# tantivy-tokenizer-api= "0.2.0"
