[package]
name = "rottnest_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rottnest_rs"
crate-type = ["cdylib"]

[features]
default = []
py = ["dep:pyo3", "pyarrow"]
pyarrow = ["arrow/pyarrow"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"], optional = true }
arrow = { version = "50.0.0", default-features = false }
tantivy = "0.21.1"
tantivy-jieba = "0.10.0"
whatlang = "0.16.4"
opendal = "0"
zstd = "0.13.0"                                          # Check for the latest version of zstd crate
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"                                          # For serialization and deserialization
regex = "1.5"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
lazy_static = "1"
bytes = "1"
thiserror = "1"


