name: Rust Build with Maturin

on: [push, pull_request]

jobs:
  build:
    name: Build Rust Project
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/pyo3/maturin

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Build with Maturin
      run: |
        rustup default stable
        maturin build --release --features py --out dist
    
    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist/*

